BROADCASTING

In [4]:
import numpy as np

a =  np.array([1,2,3]) 
print(a)

b = np.array([[4],[5],[6]])
print(b)

c=a+b
print(c)

[1 2 3]
[[4]
 [5]
 [6]]
[[5 6 7]
 [6 7 8]
 [7 8 9]]


In [8]:
import numpy as np

a =  np.array([[1],[2],[3]]) # has shape(3,1)
print(a)

b = np.array([[4,5],[6,7],[8,9]]) # has shape(3,2)
print(b)

c=a+b                             # will have shape(3,2)
print(c)

[[1]
 [2]
 [3]]
[[4 5]
 [6 7]
 [8 9]]
[[ 5  6]
 [ 8  9]
 [11 12]]


In [10]:
import numpy as np

a =  np.array([[1],[2],[3],[4]]) # has shape(4,1)
print(a)

b = np.array([[4,5],[6,7],[8,9]]) # has shape(3,2)
print(b)

c=a+b                             # will have shape(3,2)
print(c)

[[1]
 [2]
 [3]
 [4]]
[[4 5]
 [6 7]
 [8 9]]


ValueError: operands could not be broadcast together with shapes (4,1) (3,2) 

In [12]:
import numpy as np

a =  np.array([[1],[2],[3],[4]]) # has shape(4,1)
print(a)

b = np.array([[4,5],[6,7],[8,9],[10,11]]) # has shape(4,2)
print(b)

c=a+b                             # will have shape(4,2)
print(c)

[[1]
 [2]
 [3]
 [4]]
[[ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]]
[[ 5  6]
 [ 8  9]
 [11 12]
 [14 15]]


 LINEAR ALGEBRA WITH NUMPY

In [16]:
import numpy as np
a = np.array([[1,2],[3,4]])

#Determine of a matrix
det_a = np.linalg.det(a)
print('Determine of a:',det_a)

Determine of a: -2.0000000000000004


In [20]:
import numpy as np

a = np.array([[1,2,3,4],[3,4,5,6],[6,7,8,9],[2,3,4,5]])
print(a)

det_a = np.linalg.det(a)
print('Determine of a:',det_a)

[[1 2 3 4]
 [3 4 5 6]
 [6 7 8 9]
 [2 3 4 5]]
Determine of a: 0.0


In [24]:
import numpy as np

a = np.array([[13,24,35,46],[3,4,5,6],[6,7,8,9],[12,13,14,15]])
print(a)

det_a = np.linalg.det(a)
print('Determine of a:',det_a)

[[13 24 35 46]
 [ 3  4  5  6]
 [ 6  7  8  9]
 [12 13 14 15]]
Determine of a: 5.867152982581291e-30


In [36]:
# Example system of linear equations:
# 2x+y=5
# x-y=1

a = np.array([[2,1],[1,-1]])
b = np.array([5,1])
print(a)
print(b)

solutions = np.linalg.solve(a,b)
print('solution:',solutions)

[[ 2  1]
 [ 1 -1]]
[5 1]
solution: [2. 1.]


In [34]:
a = np.array([[3,1,-2],[2,-1,1],[1,2,3]])
b = np.array([9,3,12])
print(a)
print(b)
solutions = np.linalg.solve(a,b)
print("solution:",solutions)

[[ 3  1 -2]
 [ 2 -1  1]
 [ 1  2  3]]
[ 9  3 12]
solution: [2.6 3.2 1. ]


RANDOM NUMBER WITH NUMPY

In [39]:
import numpy as np

# generate a single random number between 0 and 1
random_number = np.random.rand()
print(random_number)

# generate a 1D array of 5 random number
random_array_1d = np.random.rand(5)
print(random_array_1d)

random_array_2d = np.random.rand(3,3)
print(random_array_2d)

0.9824886264085334
[0.53483103 0.98765166 0.9441194  0.33731481 0.73216254]
[[0.57788385 0.55017195 0.11792249]
 [0.68816611 0.20465267 0.56323014]
 [0.12260532 0.69599021 0.10464417]]


In [43]:
#generate  a single random integer between 0 and 10
random_int = np.random.randint(0,10)
print(random_int)

# generate a 1d array of 5 random integers between 0 and 10
random_int_array = np.random.randint(0,10, size=5)
print(random_int_array)

# generate a 2d array of 3*2 matrix random integers between 0 and 10
random_int_array_2d = np.random.randint(0,10, size=(3,2))
print(random_int_array_2d)

9
[1 5 4 6 6]
[[9 0]
 [5 2]
 [8 8]]


Random samples from a given list

In [53]:
random_sample = np.random.choice([1,2,3,4,5], size=3)
print(random_sample)

random_sample_with_replacement = np.random.choice([1,2,3,4,5], size=3, replace=True)
print(random_sample_with_replacement)

[3 4 2]
[1 4 3]


Random numbers with a specific seed (reproductibility)

In [7]:
# Set the seed for reproducibility
import numpy as np
np.random.seed(42)

# Generate random numbers
random_numbers = np.random.rand(3)
print(random_numbers)  # Corrected variable name

# Set the seed again and generate the same numbers
np.random.seed(42)
random_numbers_again = np.random.rand(3)
print(random_numbers_again)


[0.37454012 0.95071431 0.73199394]
[0.37454012 0.95071431 0.73199394]


In [9]:
!git add DAY2.ipynb

In [11]:
!git commit -m "learning day2 complete"

[main 77668ea] learning day2 complete
 1 file changed, 12 insertions(+), 17 deletions(-)


In [13]:
!git push origin main

To https://github.com/DEV-NARAYAN-SAH/MACHINELEARNING.git
 ! [rejected]        main -> main (fetch first)
error: failed to push some refs to 'https://github.com/DEV-NARAYAN-SAH/MACHINELEARNING.git'
hint: Updates were rejected because the remote contains work that you do not
hint: have locally. This is usually caused by another repository pushing to
hint: the same ref. If you want to integrate the remote changes, use
hint: 'git pull' before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
