NumPy Array Indexing

Access Array Elements
Array indexing is the same as accessing an array element.

You can access an array element by referring to its index number.

The indexes in NumPy arrays start with 0, meaning that the first element has index 0, and the second has index 1 etc.

In [9]:
import numpy as np

a = np.array([1,2,3,4,5])
print(a[0])

1


In [11]:
print(a[1])

2


In [13]:
print(a[2])
print(a[3])
print(a[2]+a[3])

3
4
7


Access 2-D Arrays
To access elements from 2-D arrays we can use comma separated integers representing the dimension and the index of the element.

Think of 2-D arrays like a table with rows and columns, where the dimension represents the row and the index represents the column.

In [16]:
import numpy as np

a = np.array([[1,2,3,4,5],[6,7,8,9,10]])

print(a)
print(a[0,1])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
2


In [20]:
print(a[0,0])
print(a[0,1])
print(a[0,2])
print(a[0,3])
print(a[0,4])
print(a[1,0])
print(a[1,1])
print(a[1,2])
print(a[1,3])
print(a[1,4])


1
2
3
4
5
6
7
8
9
10


Access 3-D Arrays
- To access elements from 3-D arrays we can use comma separated integers representing the dimensions and the index of the element.

In [25]:
import numpy as np

a = np.array([[[1,2,3],[4,5,6]],[[2,3,4],[5,6,7]]])
print(a)
print(a[0,1,2])

[[[1 2 3]
  [4 5 6]]

 [[2 3 4]
  [5 6 7]]]
6


In [33]:
print(a[0,0,0])
print(a[0,0,1])
print(a[0,0,2])
print(a[0,1,0])
print(a[0,1,1])
print(a[0,1,2])
print(a[1,0,0])
print(a[1,0,1])
print(a[1,0,2])
print(a[1,1,0])
print(a[1,1,1])
print(a[1,1,2])




1
2
3
4
5
6
2
3
4
5
6
7


Negative Indexing
- Use negative indexing to access an array from the end.

In [36]:
import numpy as np

a = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [38]:
print(a[1,-1])

10


In [44]:
print(a[1,-1])
print(a[1,-2])
print(a[1,-3])
print(a[1,-4])
print(a[1,-5])
print(a[0,-1])
print(a[0,-2])
print(a[0,-3])
print(a[0,-4])
print(a[0,-5])

10
9
8
7
6
5
4
3
2
1


NumPy Array Slicing


Slicing arrays
- Slicing in python means taking elements from one given index to another given index.

- We pass slice instead of index like this: [start:end].

- We can also define the step, like this: [start:end:step].

- If we don't pass start its considered 0

- If we don't pass end its considered length of array in that dimension

- If we don't pass step its considered 1



In [48]:
import numpy as np

a = np.array([1,2,3,4,5,6,7])
print(a[1:5])

[2 3 4 5]


In [55]:
print(a[4:])

[5 6 7]


In [57]:
print(a[:4])

[1 2 3 4]


Negative Slicing
- Use the minus operator to refer to an index from the end:

In [60]:
import numpy as np

a = np.array([1,2,3,4,5,6,7])

print(a[-3:-1])

[5 6]


STEP
- Use the step value to determine the step of the slicing:

In [65]:
import numpy as np

a = np.array([1,2,3,4,5,6,7])

print(a[1:5:2])

[2 4]


In [67]:
print(a[1:6:3])

[2 5]


In [69]:
print(a[::2])

[1 3 5 7]


Slicing 2-D Arrays

In [72]:
import numpy as np

a = np.array([[1,2,3,4,5],[6,7,8,9,10]])

print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [74]:
print(a[1,1:4])

[7 8 9]


In [76]:
print(a[1,:5])

[ 6  7  8  9 10]


In [78]:
print(a[0:2,2])

[3 8]


In [80]:
print(a[0:2, 1:4])

[[2 3 4]
 [7 8 9]]
