In [1]:
!git add devnumpy.ipynb

In [3]:
!git commit -m "selfpractice day 1 complete"

[main 5c1f551] selfpractice day 1 complete
 1 file changed, 33 insertions(+)
 create mode 100644 devnumpy.ipynb


In [5]:
!git push origin main

To https://github.com/DEV-NARAYAN-SAH/MACHINELEARNING.git
   8750c0b..5c1f551  main -> main


In [7]:
import numpy as np

In [11]:
import numpy as np

a = np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [13]:
import numpy as np

print(np.__version__)

1.26.4


In [15]:
import numpy as np

a = np.array([1,2,3,4,5])
print(a)

print(type(a))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [17]:
a = np.array((1,2,3,4,5))
print(a)

[1 2 3 4 5]


0-D ARRAYS

In [22]:
import numpy as np

a = np.array(42)

print(a)

42


1-D ARRAYS

In [27]:
import numpy as np

a = np.array([1,2,3,4,5])

print(a)

[1 2 3 4 5]


2-D ARRAYS

In [37]:
import numpy as np

a = np.array([[1,2,3],[4,5,6]])
print(a)
print(a.ndim)

[[1 2 3]
 [4 5 6]]
2


3-D ARRAY

In [33]:
import numpy as np

a = np.array([[[1,2],[3,4]],[[6,7],[8,9]]])
print(a)

[[[1 2]
  [3 4]]

 [[6 7]
  [8 9]]]


In [35]:
print(a.ndim)

3


In [41]:
import numpy as np

a = np.array([1,2,3,4,5], ndmin=5)

print(a)
print('the number of dimensions:',a.ndim)

[[[[[1 2 3 4 5]]]]]
the number of dimensions: 5


In [45]:
import numpy as np

a = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(a)
print(a[1,1,0])

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
7


In [47]:
a = np.array([1,2,3,4,5])
print(a[0])

1


In [51]:
print(a[1])

2


In [53]:
print(a[0]+a[3])

5


In [59]:
import numpy as np 

a = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(a)
print('2nd element on 1st row:', a[0,1])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
2nd element on 1st row: 2


In [61]:
print(a[0,2])

3


In [63]:
print(a[1,2])

8


In [65]:
print(a[1,4])

10


In [69]:
import numpy as np

a = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(a)
print(a[0,1,2])

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
6


In [71]:
print(a[1,1,1])

11


In [99]:
print(a[0,0,0])
print(a[0,0,1])
print(a[0,0,2])
print(a[0,1,0])
print(a[0,1,1])
print(a[0,1,2])
print(a[1,0,0])
print(a[1,0,1])
print(a[1,0,2])
print(a[1,1,0])
print(a[1,1,1])
print(a[1,1,2])

1
2
3
4
5
6
7
8
9
10
11
12


In [103]:
import numpy as np

a = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [113]:
print(a[1,-1])
print(a[1,-2])
print(a[1,-3])
print(a[1,-4])
print(a[1,-5])


10
9
8
7
6


In [115]:
print(a[0,-1])
print(a[0,-2])
print(a[0,-3])
print(a[0,-4])
print(a[0,-5])


5
4
3
2
1


In [111]:
print(a[0,0])
print(a[0,1])
print(a[0,2])
print(a[0,3])
print(a[0,4])
print(a[1,0])
print(a[1,1])
print(a[1,2])
print(a[1,3])
print(a[1,4])


1
2
3
4
5
6
7
8
9
10


In [117]:
!git add devnumpy.ipynb

In [119]:
!git commit -m 'practice day 1'

error: pathspec 'day' did not match any file(s) known to git
error: pathspec '1'' did not match any file(s) known to git


In [121]:
!get commit -m "selfpractice day1"

'get' is not recognized as an internal or external command,
operable program or batch file.


In [123]:
!git push origin main

Everything up-to-date
