NumPy Data Types


Data Types in Python
- By default Python have these data types:

- strings - used to represent text data, the text is given under quote marks. e.g. "ABCD"
- integer - used to represent integer numbers. e.g. -1, -2, -3
- float - used to represent real numbers. e.g. 1.2, 42.42
- boolean - used to represent True or False.
- complex - used to represent complex numbers. e.g. 1.0 + 2.0j, 1.5 + 2.5j
- Data Types in NumPy
- NumPy has some extra data types, and refer to data types with one character, like i for integers, u for unsigned integers etc.

- Below is a list of all data types in NumPy and the characters used to represent them.

- i - integer
- b - boolean
- u - unsigned integer
- f - float
- c - complex float
- m - timedelta
- M - datetime
- O - object
- S - string
- U - unicode string
- V - fixed chunk of memory for other type ( void )


Checking the Data Type of an Array
- The NumPy array object has a property called dtype that returns the data type of the array:

In [12]:
import numpy as np
a = np.array([1,2,3,4,5])
print(a)
print(a.dtype)

[1 2 3 4 5]
int32


In [14]:
import numpy as np

a = np.array(['apple','banana','grape','orange'])
print(a)
print(a.dtype)

['apple' 'banana' 'grape' 'orange']
<U6


Creating Arrays With a Defined Data Type
- We use the array() function to create arrays, this function can take an optional argument: 
dtype that allows us to define the expected data type of the array elements:

In [19]:
import numpy as np
a = np.array([1,2,3,4,5], dtype='S')

print(a)
print(a.dtype)


[b'1' b'2' b'3' b'4' b'5']
|S1


For i, u, f, S and U we can define size as well.



In [26]:
import numpy as np
a = np.array([1,2,3,4,5], dtype='i4')

print(a)
print(a.dtype)


[1 2 3 4 5]
int32


In [28]:
import numpy as np 

a = np.array(['a','2','3'], dtype='i4')

print(a)

ValueError: invalid literal for int() with base 10: 'a'

Converting Data Type on Existing Arrays
The best way to change the data type of an existing array, is to make a copy of the array with the astype() method.

The astype() function creates a copy of the array, and allows you to specify the data type as a parameter.

The data type can be specified using a string, like 'f' for float, 'i' for integer etc. or you can use the data type directly like float for float and int for integer.

In [31]:
import numpy as np
a = np.array([1.1,2.2,3.3])
newa = a.astype('i')
print(newa)
print(newa.dtype)

[1 2 3]
int32


In [33]:
import numpy as np
a = np.array([1.1,2.2,3.3])
newa = a.astype(int)
print(newa)
print(newa.dtype)

[1 2 3]
int32


In [35]:
import numpy as np
a = np.array([1,0,3])
newa = a.astype(bool)
print(newa)
print(newa.dtype)

[ True False  True]
bool


NumPy Array Copy vs View


The Difference Between Copy and View
The main difference between a copy and a view of an array is that the copy is a new array, and the view is just a view of the original array.

The copy owns the data and any changes made to the copy will not affect original array, and any changes made to the original array will not affect the copy.

The view does not own the data and any changes made to the view will affect the original array, and any changes made to the original array will affect the view.



COPY:
Example

In [42]:
import numpy as np

a = np.array([1,2,3,4,5])

x = a.copy()
a[0] = 43
print(a)
print(x)

[43  2  3  4  5]
[1 2 3 4 5]


VIEW:

In [45]:
import numpy as np

a = np.array([1,2,3,4,5])

x = a.view()
a[0] = 43
print(a)
print(x)

[43  2  3  4  5]
[43  2  3  4  5]


Make Changes in the VIEW:

In [48]:
import numpy as np

a = np.array([1,2,3,4,5])

x = a.view()
a[0] = 22
print(a)
print(x)

[22  2  3  4  5]
[22  2  3  4  5]


Check if Array Owns its Data

As mentioned above, copies owns the data, and views does not own the data, but how can we check this?

Every NumPy array has the attribute base that returns None if the array owns the data.

Otherwise, the base  attribute refers to the original object.

In [51]:
import numpy as np

a = np.array([1,2,3,4,5])

x = a.copy()
y = a.view()
print(x.base)
print(y.base)

None
[1 2 3 4 5]


In [53]:
!git pull

Already up to date.


In [55]:
!git add devnumpy3.ipynb

In [57]:
!git commit -m "third day of learning numpy completed"

[main e9264cf] third day of learning numpy completed
 1 file changed, 464 insertions(+)
 create mode 100644 devnumpy3.ipynb


In [59]:
!git push origin main

To https://github.com/DEV-NARAYAN-SAH/MACHINELEARNING.git
   c068572..e9264cf  main -> main
